//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chemistry.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chemistry.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actinide.
        /// </summary>
        public static string Actinide {
            get {
                return ResourceManager.GetString("Actinide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actinides.
        /// </summary>
        public static string Actinides {
            get {
                return ResourceManager.GetString("Actinides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alkaline.
        /// </summary>
        public static string Alkaline {
            get {
                return ResourceManager.GetString("Alkaline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alkaline-earth.
        /// </summary>
        public static string AlkalineEarth {
            get {
                return ResourceManager.GetString("AlkalineEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alkaline.
        /// </summary>
        public static string Alkalines {
            get {
                return ResourceManager.GetString("Alkalines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alkaline-earth.
        /// </summary>
        public static string AlkalinesEarth {
            get {
                return ResourceManager.GetString("AlkalinesEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atomic.
        /// </summary>
        public static string Atomic {
            get {
                return ResourceManager.GetString("Atomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atomic number.
        /// </summary>
        public static string AtomicNumber {
            get {
                return ResourceManager.GetString("AtomicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boiling point.
        /// </summary>
        public static string BoilingPoint {
            get {
                return ResourceManager.GetString("BoilingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical.
        /// </summary>
        public static string Chemical {
            get {
                return ResourceManager.GetString("Chemical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry.
        /// </summary>
        public static string Chemistry {
            get {
                return ResourceManager.GetString("Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combine.
        /// </summary>
        public static string Combine {
            get {
                return ResourceManager.GetString("Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound.
        /// </summary>
        public static string Compound {
            get {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to covalent radius.
        /// </summary>
        public static string CovalentRadius {
            get {
                return ResourceManager.GetString("CovalentRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decompose.
        /// </summary>
        public static string Decompose {
            get {
                return ResourceManager.GetString("Decompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decomposition.
        /// </summary>
        public static string Decomposition {
            get {
                return ResourceManager.GetString("Decomposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to density at 0 ⁰C (273 К).
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electronegativity.
        /// </summary>
        public static string Electronegativity {
            get {
                return ResourceManager.GetString("Electronegativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elements.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange.
        /// </summary>
        public static string Exchanging {
            get {
                return ResourceManager.GetString("Exchanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit from test?.
        /// </summary>
        public static string ExitFromTest {
            get {
                return ResourceManager.GetString("ExitFromTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first substance.
        /// </summary>
        public static string FirstSubstance {
            get {
                return ResourceManager.GetString("FirstSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to halogen.
        /// </summary>
        public static string Halogen {
            get {
                return ResourceManager.GetString("Halogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to halogens.
        /// </summary>
        public static string Halogens {
            get {
                return ResourceManager.GetString("Halogens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heat of melting.
        /// </summary>
        public static string HeatOfMelting {
            get {
                return ResourceManager.GetString("HeatOfMelting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heat of vaporization.
        /// </summary>
        public static string HeatOfVaporization {
            get {
                return ResourceManager.GetString("HeatOfVaporization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inert gas.
        /// </summary>
        public static string InertGas {
            get {
                return ResourceManager.GetString("InertGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inert gases.
        /// </summary>
        public static string InertGases {
            get {
                return ResourceManager.GetString("InertGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ionization energy.
        /// </summary>
        public static string IonizationEnergy {
            get {
                return ResourceManager.GetString("IonizationEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ion radius.
        /// </summary>
        public static string IonRadius {
            get {
                return ResourceManager.GetString("IonRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lanthanide.
        /// </summary>
        public static string Lanthanide {
            get {
                return ResourceManager.GetString("Lanthanide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lanthanides.
        /// </summary>
        public static string Lanthanides {
            get {
                return ResourceManager.GetString("Lanthanides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to melting point.
        /// </summary>
        public static string MeltingPoint {
            get {
                return ResourceManager.GetString("MeltingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must purchase the unlimited pack of the application to access this reaction..
        /// </summary>
        public static string MessagePurchaseForReaction {
            get {
                return ResourceManager.GetString("MessagePurchaseForReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must purchase the unlimited pack of the application to access this table..
        /// </summary>
        public static string MessagePurchaseForTable {
            get {
                return ResourceManager.GetString("MessagePurchaseForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must purchase the unlimited pack of the application to access this test..
        /// </summary>
        public static string MessagePurchaseForTest {
            get {
                return ResourceManager.GetString("MessagePurchaseForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase the unlimited pack now?.
        /// </summary>
        public static string MessagePurchasePack {
            get {
                return ResourceManager.GetString("MessagePurchasePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your purchase..
        /// </summary>
        public static string MessageThanksForPurchase {
            get {
                return ResourceManager.GetString("MessageThanksForPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metals.
        /// </summary>
        public static string Metals {
            get {
                return ResourceManager.GetString("Metals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D-model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to molar heat capacity.
        /// </summary>
        public static string MolarHeatCapacity {
            get {
                return ResourceManager.GetString("MolarHeatCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to molar volume.
        /// </summary>
        public static string MolarVolume {
            get {
                return ResourceManager.GetString("MolarVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to molecular weight.
        /// </summary>
        public static string MolecularWeight {
            get {
                return ResourceManager.GetString("MolecularWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonmetal.
        /// </summary>
        public static string NonMetal {
            get {
                return ResourceManager.GetString("NonMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonmetals.
        /// </summary>
        public static string NonMetals {
            get {
                return ResourceManager.GetString("NonMetals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oxidation degree.
        /// </summary>
        public static string OxidationDegree {
            get {
                return ResourceManager.GetString("OxidationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERIODIC.
        /// </summary>
        public static string Periodic {
            get {
                return ResourceManager.GetString("Periodic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post transitional.
        /// </summary>
        public static string PostTransitional {
            get {
                return ResourceManager.GetString("PostTransitional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post transitional.
        /// </summary>
        public static string PostTransitionals {
            get {
                return ResourceManager.GetString("PostTransitionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reactions.
        /// </summary>
        public static string Reactions {
            get {
                return ResourceManager.GetString("Reactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must restart the application.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second substance.
        /// </summary>
        public static string SecondSubstance {
            get {
                return ResourceManager.GetString("SecondSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semimetal.
        /// </summary>
        public static string SemiMetal {
            get {
                return ResourceManager.GetString("SemiMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semimetals.
        /// </summary>
        public static string SemiMetals {
            get {
                return ResourceManager.GetString("SemiMetals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLUBILITY.
        /// </summary>
        public static string Solubility {
            get {
                return ResourceManager.GetString("Solubility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subgroup.
        /// </summary>
        public static string Subgroup {
            get {
                return ResourceManager.GetString("Subgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substance.
        /// </summary>
        public static string Substance {
            get {
                return ResourceManager.GetString("Substance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSTANCES.
        /// </summary>
        public static string Substances {
            get {
                return ResourceManager.GetString("Substances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substitute.
        /// </summary>
        public static string Substitute {
            get {
                return ResourceManager.GetString("Substitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substitution.
        /// </summary>
        public static string Substitution {
            get {
                return ResourceManager.GetString("Substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thermal conductivity.
        /// </summary>
        public static string ThermalConductivity {
            get {
                return ResourceManager.GetString("ThermalConductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thermodinamical.
        /// </summary>
        public static string Thermodinamical {
            get {
                return ResourceManager.GetString("Thermodinamical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transitional.
        /// </summary>
        public static string Transitional {
            get {
                return ResourceManager.GetString("Transitional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transitional.
        /// </summary>
        public static string Transitionals {
            get {
                return ResourceManager.GetString("Transitionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlimited pack.
        /// </summary>
        public static string UnlimitedPack {
            get {
                return ResourceManager.GetString("UnlimitedPack", resourceCulture);
            }
        }
    }
}
